import axios from "axios"

// MOVIES
const FETCH_MOVIE_ACTION = ""
const FETCH_MOVIE_ROMANCE = ""
const FETCH_MOVIE_HORROR = ""
const FETCH_MOVIE_FAMILY = ""
const FETCH_MOVIE_THRILLER = ""
const FETCH_MOVIE_HISTORY = ""
const FETCH_MOVIE_FANTASY = ""
const FETCH_MOVIE_WAR = ""
const FETCH_MOVIE_ADVENTURE = ""

// SERIES
const FETCH_SERIES_ACTION = ""

export {
    FETCH_MOVIE_ACTION,
    FETCH_MOVIE_ROMANCE,
    FETCH_MOVIE_HORROR,
    FETCH_MOVIE_FAMILY,
    FETCH_MOVIE_THRILLER,
    FETCH_MOVIE_HISTORY,
    FETCH_MOVIE_FANTASY,
    FETCH_MOVIE_WAR,
    FETCH_MOVIE_ADVENTURE,
    FETCH_SERIES_ACTION
};