import {
    FETCH_MOVIE_ACTION,
    FETCH_MOVIE_ROMANCE,
    FETCH_MOVIE_HORROR,
    FETCH_MOVIE_FAMILY,
    FETCH_MOVIE_THRILLER,
    FETCH_MOVIE_HISTORY,
    FETCH_MOVIE_FANTASY,
    FETCH_MOVIE_WAR,
    FETCH_MOVIE_ADVENTURE,
    FETCH_SERIES_ACTION
} from './action'

console.log("MOVIE_ACTION", FETCH_MOVIE_ACTION())